# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 126b19f5a5007b917f5839fcc32124ff8baff81fc5e732326b6cff8350b75c9785571e88464bbb586fb1cc9c356aac88903361a7404384da9b2124eb70f8b8ac

test:
  secret_key_base: 9cf653121d1eea73f62c09d8da9ebd8beb9bd6b7d0eb1611758cd75cab931d754ce41522ef646152975100dbc27cbc2263f28a5bfff3dda082267ed4b27aecb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
